// react/src/components/GetBeer.tsx
import * as React from 'react'

import './GetBeer.css'

interface IProps {
  getBeer: () => void
  beers: any[]
  isLoading: boolean
}

const GetBeer = (props: IProps) => (
  <div className="get-beer">
    <button onClick={props.getBeer} type="button" className="get-beer__button">
      Show me the beers!
    </button>
    {props.isLoading && (
      <div className="get-beer__spinner">
        <p>Fetching beer... be patient!</p>
      </div>
    )}
    <div className="get-beer__beers">
      <ol className="get-beer__beers-list">
        {props.beers.map(beer => (
          <li className="get-beer__beers-list-item" key={beer.id}>
            <div className="get-beer__beers-list-item--beer-name">
              {beer.name}
            </div>
            <div className="get-beer__beers-list-item--beer-tagline">
              {beer.tagline}
            </div>
          </li>
        ))}
      </ol>
    </div>
  </div>
)

export default GetBeer

// angular/src/app/components/get-beer/get-beer.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subscription } from 'rxjs';
import type { Beer, BeerState } from '../../../types/beer';
import { getBeer } from '../../../app/reducers/beer.reducer';

@Component({
  selector: 'app-get-beer',
  templateUrl: './get-beer.component.html',
  styleUrls: ['./get-beer.component.css'],
})
export class GetBeerComponent implements OnInit, OnDestroy {
  private beerSub: Subscription | undefined = undefined;

  public beers: Beer[] = [];
  public isLoading: boolean = false;

  constructor(private store: Store<any>) {}

  ngOnInit() {
    this.beerSub = this.store
      .select('beers')
      .subscribe((beerState: BeerState) => {
        this.beers = beerState.beers;
        this.isLoading = beerState.isLoading;
      });
  }

  ngOnDestroy() {
    this.beerSub?.unsubscribe();
  }

  getBeer(event: Event) {
    event.preventDefault();
    this.store.dispatch(getBeer());
  }
}

<div class="get-beer">
  <button type="button" (click)="getBeer($event)" class="get-beer__button">
    Show me the beers!
  </button>
  <div *ngIf="isLoading" class="get-beer__spinner">
    <p>Fetching beer... be patient!</p>
  </div>
  <div *ngIf="beers" class="get-beer__beers">
    <ol class="get-beer__beers-list">
      <li *ngFor="let beer of beers" class="get-beer__beers-list-item">
        <div class="get-beer__beers-list-item--beer-name">{{ beer.name }}</div>
        <div class="get-beer__beers-list-item--beer-tagline">
          {{ beer.tagline }}
        </div>
      </li>
    </ol>
  </div>
</div>
