// vue/src/App.vue
<script setup lang="ts">
import HomeView from '@/views/Home.vue'
</script>

<template>
  <main className="app">
    <h1 className="app__heading">Welcome to the Get Beer app!</h1>
    <HomeView />
  </main>
</template>

<style scoped>
.app {
  margin: 0 auto;
  max-width: 640px;
}

.app__heading {
}
</style>

// react/src/App.tsx
import * as React from 'react'
import { QueryClient, QueryClientProvider } from 'react-query'
import { GetBeer } from 'components/GetBeer'
import './App.css'

const queryClient = new QueryClient()

const App = () => (
  <QueryClientProvider client={queryClient}>
    <main className="app">
      <h1 className="app__heading">Welcome to the Get Beer app!</h1>
      <GetBeer />
    </main>
  </QueryClientProvider>
)

export default App
